### ISSUE TITLE
No Longer Working: Cannot Import Name 'coverage'

### ISSUE THREAD

**Issue by rdegges** [z4r/python-coveralls#40] opened 2015-10-02 21:00 UTC
I'm attempting to use this library with the latest release, but am having issues. It looks like some internal stuff is breaking via imports:

<img width="954" alt="screenshot 2015-10-02 13 58 30" src="https://cloud.githubusercontent.com/assets/90247/10257709/d56f24b6-690d-11e5-8cf6-31d37bb917c9.png">

This happens for every version of python on travis :(

**Comment by ismail-s** [comment] 2015-10-14 12:23
@rdegges This looks like a dupe of #39 .

**Comment by z4r** [comment] 2015-10-14 13:42
Yes, it's a dupe of #39.

**Closed by z4r** 2015-10-14 13:42 UTC
